apiVersion: batch/v1
kind: Job
metadata:
  name: bad_jobs
spec:
  template:
    metadata:
      name: bad_jobs_meta
    spec:
      restartPolicy: Never
      containers:
      - name: box
        image: alpine
        command: ["/bin/sh", "-c", "exit 1"]
        
