...
spec:
  containers:
  - image: ghost:4.7.3-apache
    name: ghost
    env:
      - name: GHOST_DB_HOST
        value: ghost-mysql
      - name: GHOST_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: ghost-password
            key: password.txt
